language: node_js
dist: trusty
node_js: lts/*

addons:
  chrome: stable

cache: yarn

install:
  - yarn install

script:
  # xvfb-run is needed for headless testing with real browsers
  - xvfb-run karma start --single-run

  - if [[ "$TRAVIS_EVENT_TYPE" = "push" ]]; then
      karma start --single-run --sauce;
    fi;

notifications:
  email:
    on_success: never
